name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ["3.10", "3.12"]
        llvm-version: [20]
    env:
      CC: clang-${{ matrix.llvm-version }}
      CXX: clang++-${{ matrix.llvm-version }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - uses: bazel-contrib/setup-bazel@0.14.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
        repository-cache: true

    - name: Set min macOS version
      if: runner.os == 'macOS'
      run: |
        echo "MACOSX_DEPLOYMENT_TARGET=11.0" >> $GITHUB_ENV

    - name: Install latest Clang on macOS.
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install llvm@${{ matrix.llvm-version }}
        echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

    - name: Install python3-dev on Ubuntu.
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt install python3-dev

    - name: Install Clang-20 on Ubuntu.
      if: runner.os == 'Linux'
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${{ matrix.llvm-version }} all
        sudo apt-get update

    - name: Build and install
      run: |
        python -m pip install --upgrade pip
        python -m pip install 'pytest' 'jax[cpu]'
        pip install --verbose .

    - name: Test
      run: python -m pytest
